name: Tests lecture 7 airline

on: push

jobs:
  test_project:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run Django unit tests
      run: |
        cd lecture7
        pip3 install --user django
        python3 manage.py test
